"resource/ui/main_menu/OptionsDialog.res"
{
	"CTFOptionsDialog"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"CTFOptionsDialog"
		"xpos"				"c-255"
		"ypos"				"c-205"
		"wide"				"510"
		"tall"				"410"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"bordervisible"		"0"
		"bgcolor_override"	"0 0 0 0"
	}
	
	"Background"
	{
		"ControlName"	"EditablePanel"
		"fieldName"	"Background"
		"xpos"		"5"
		"ypos"		"5"
		"zpos"		"-2"
		"wide"		"500"
		"tall"		"400"
		"visible"	"1"
		"enabled"	"1"
		"bgcolor_override"	"MainMenuBackground"
	}
	
	"BackgroundBorder"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"BackgroundBorder"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"509"
		"tall"			"409"
		"visible"		"1"
		"enabled"		"1"
		"border"			"OuterShadowBorder"
	}
	
	"InnerShadow"
	{
		"ControlName"			"EditablePanel"
		"fieldName"			"InnerShadow"
		"xpos"				"25"
		"ypos"				"55"
		"zpos"				"1"
		"wide"				"460"
		"tall"				"310"
		"visible"			"1"
		"enabled"			"1"
		"border"				"InnerShadowBorder"
		"mouseinputenabled"	"0"
	}
	
	"OK"
	{
		"ControlName"	"CTFButton"
		"fieldName"		"OK"
		"xpos"			"265"
		"ypos"			"373"
		"zpos"			"2"
		"wide"			"70"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"command"		"Ok"	
		"labelText" 		"#GameUI_OK"
		"textAlignment"		"center"
		"font"				"TF2CMenuButton"
		"defaultFgColor_override"		"ButtonLabelMM"
		"armedFgColor_override"		"ButtonArmedLabelMM"
		"depressedFgColor_override"	"ButtonDepressedLabelMM"
		"disabledFgColor_override"		"ButtonDisabledLabelMM"
		"border_default"	"MainMenuAdvSquareButtonDefault"
		"border_armed"	"MainMenuAdvSquareButtonArmed"
		"border_depressed" "MainMenuAdvSquareButtonDepressed"
		"border_disabled" "MainMenuAdvSquareButtonDepressed"
	}
	
	"Cancel"
	{
		"ControlName"	"CTFButton"
		"fieldName"		"Cancel"
		"xpos"			"340"
		"ypos"			"373"
		"zpos"			"2"
		"wide"			"70"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"command"		"vguicancel"
		"labelText" 		"#GameUI_Cancel"
		"textAlignment"		"center"
		"font"				"TF2CMenuButton"
		"defaultFgColor_override"		"ButtonLabelMM"
		"armedFgColor_override"		"ButtonArmedLabelMM"
		"depressedFgColor_override"	"ButtonDepressedLabelMM"
		"disabledFgColor_override"		"ButtonDisabledLabelMM"
		"border_default"	"MainMenuAdvSquareButtonDefault"
		"border_armed"	"MainMenuAdvSquareButtonArmed"
		"border_depressed" "MainMenuAdvSquareButtonDepressed"
		"border_disabled" "MainMenuAdvSquareButtonDisabled"
	}	
	
	"Apply"
	{
		"ControlName"	"CTFButton"
		"fieldName"		"Apply"
		"xpos"			"415"
		"ypos"			"373"
		"zpos"			"2"
		"wide"			"70"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"0"
		"command"		"Apply"
		"labelText" 		"#GameUI_Apply"
		"textAlignment"		"center"
		"font"				"TF2CMenuButton"
		"defaultFgColor_override"		"ButtonLabelMM"
		"armedFgColor_override"		"ButtonArmedLabelMM"
		"depressedFgColor_override"	"ButtonDepressedLabelMM"
		"disabledFgColor_override"		"ButtonDisabledLabelMM"
		"border_default"	"MainMenuAdvSquareButtonDefault"
		"border_armed"	"MainMenuAdvSquareButtonArmed"
		"border_depressed" "MainMenuAdvSquareButtonDepressed"
		"border_disabled" "MainMenuAdvSquareButtonDisabled"
	}

	"Defaults"
	{
		"ControlName"		"CTFButton"
		"fieldName"			"Defaults"
		"xpos"				"25"
		"ypos"				"373"
		"wide"				"120"
		"tall"				"20"
		"visible"			"0"
		"enabled"			"1"
		"Command"			"DefaultsOK"
		"labelText" 		"#GameUI_UseDefaults"
		"textAlignment"		"center"
		"font"				"TF2CMenuButton"
		"defaultFgColor_override"		"ButtonLabelMM"
		"armedFgColor_override"		"ButtonArmedLabelMM"
		"depressedFgColor_override"	"ButtonDepressedLabelMM"
		"disabledFgColor_override"		"ButtonDisabledLabelMM"
		"border_default"	"MainMenuAdvSquareButtonDefault"
		"border_armed"	"MainMenuAdvSquareButtonArmed"
		"border_depressed" "MainMenuAdvSquareButtonDepressed"
		"border_disabled" "MainMenuAdvSquareButtonDisabled"
	}
	
	"optionsbutton"
	{
		"ControlName"		"CAdvTabs"
		"fieldName"			"optionsbutton"
		"xpos"				"72"
		"ypos"				"19"
		"zpos"				"6"
		"wide"				"366"
		"tall"				"25"
		"visible"			"1"
		"enabled"			"1"
		"bordervisible"		"0"		
		
		"AdvButton"
		{
			"ControlName"		"CTFButton"
			"fieldName"			"AdvButton"
			"xpos"				"0"
			"ypos"				"0"
			"wide"				"80"
			"tall"				"25"
			"visible"			"1"
			"enabled"			"1"
			"command"				"newoptionsadv"
			"labelText"			"#GameUI_TitleAdvanced"
			"stayselectedonclick"	"1"
			"textAlignment"		"center"	
			"font"				"TF2CMenuButton"
			"defaultFgColor_override"		"ButtonLabelMM"
			"armedFgColor_override"		"ButtonArmedLabelMM"
			"depressedFgColor_override"	"ButtonDepressedLabelMM"
			"disabledFgColor_override"		"ButtonDisabledLabelMM"
			"selectedFgColor_override"		"ButtonArmedLabelMM"
			"border_default"	"MainMenuAdvSquareButtonDefault"
			"border_armed"	"MainMenuAdvSquareButtonArmed"
			"border_depressed" "MainMenuAdvSquareButtonDepressed"
			"border_disabled" "MainMenuAdvSquareButtonDisabled"
			"bordervisible"			"1"
		}	
		
		"MouseButton"
		{
			"ControlName"		"CTFButton"
			"fieldName"			"MouseButton"
			"pin_to_sibling"		"AdvButton"
			"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
			"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
			"xpos"				"4"
			"ypos"				"0"
			"wide"				"70"
			"tall"				"25"
			"visible"			"1"
			"enabled"			"1"
			"command"				"newoptionsmouse"
			"labelText"			"#GameUI_TitleMouse"
			"stayselectedonclick"	"1"
			"textAlignment"		"center"	
			"font"				"TF2CMenuButton"
			"defaultFgColor_override"		"ButtonLabelMM"
			"armedFgColor_override"		"ButtonArmedLabelMM"
			"depressedFgColor_override"	"ButtonDepressedLabelMM"
			"disabledFgColor_override"		"ButtonDisabledLabelMM"
			"selectedFgColor_override"		"ButtonArmedLabelMM"
			"border_default"	"MainMenuAdvSquareButtonDefault"
			"border_armed"	"MainMenuAdvSquareButtonArmed"
			"border_depressed" "MainMenuAdvSquareButtonDepressed"
			"border_disabled" "MainMenuAdvSquareButtonDisabled"
			"bordervisible"			"1"
		}
		
		"KeyboardButton"
		{
			"ControlName"		"CTFButton"
			"fieldName"			"KeyboardButton"
			"pin_to_sibling"		"MouseButton"
			"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
			"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
			"xpos"				"4"
			"ypos"				"0"
			"wide"				"70"
			"tall"				"25"
			"visible"			"1"
			"enabled"			"1"
			"command"				"newoptionskeyboard"
			"labelText"			"#GameUI_TitleKeyboard"
			"stayselectedonclick"	"1"
			"textAlignment"		"center"
			"font"				"TF2CMenuButton"
			"defaultFgColor_override"		"ButtonLabelMM"
			"armedFgColor_override"		"ButtonArmedLabelMM"
			"depressedFgColor_override"	"ButtonDepressedLabelMM"
			"disabledFgColor_override"		"ButtonDisabledLabelMM"
			"selectedFgColor_override"		"ButtonArmedLabelMM"
			"border_default"	"MainMenuAdvSquareButtonDefault"
			"border_armed"	"MainMenuAdvSquareButtonArmed"
			"border_depressed" "MainMenuAdvSquareButtonDepressed"
			"border_disabled" "MainMenuAdvSquareButtonDisabled"
			"bordervisible"			"1"
		}
		
		"AudioButton"
		{
			"ControlName"		"CTFButton"
			"fieldName"			"AudioButton"
			"pin_to_sibling"		"KeyboardButton"
			"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
			"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
			"xpos"				"4"
			"ypos"				"0"
			"wide"				"60"
			"tall"				"25"
			"visible"			"1"
			"enabled"			"1"
			"command"				"newoptionsaudio"
			"labelText"			"#GameUI_TitleAudio"
			"stayselectedonclick"	"1"
			"textAlignment"		"center"	
			"font"				"TF2CMenuButton"
			"defaultFgColor_override"		"ButtonLabelMM"
			"armedFgColor_override"		"ButtonArmedLabelMM"
			"depressedFgColor_override"	"ButtonDepressedLabelMM"
			"disabledFgColor_override"		"ButtonDisabledLabelMM"
			"selectedFgColor_override"		"ButtonArmedLabelMM"
			"border_default"	"MainMenuAdvSquareButtonDefault"
			"border_armed"	"MainMenuAdvSquareButtonArmed"
			"border_depressed" "MainMenuAdvSquareButtonDepressed"
			"border_disabled" "MainMenuAdvSquareButtonDisabled"
			"bordervisible"			"1"
		}
		
		"VideoButton"
		{
			"ControlName"		"CTFButton"
			"fieldName"			"VideoButton"
			"pin_to_sibling"		"AudioButton"
			"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
			"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
			"xpos"				"4"
			"ypos"				"0"
			"wide"				"70"
			"tall"				"25"
			"visible"			"1"
			"enabled"			"1"
			"command"				"newoptionsvideo"
			"labelText"			"#GameUI_TitleVideo"
			"stayselectedonclick"	"1"
			"textAlignment"		"center"	
			"font"				"TF2CMenuButton"
			"defaultFgColor_override"		"ButtonLabelMM"
			"armedFgColor_override"		"ButtonArmedLabelMM"
			"depressedFgColor_override"	"ButtonDepressedLabelMM"
			"disabledFgColor_override"		"ButtonDisabledLabelMM"
			"selectedFgColor_override"		"ButtonArmedLabelMM"
			"border_default"	"MainMenuAdvSquareButtonDefault"
			"border_armed"	"MainMenuAdvSquareButtonArmed"
			"border_depressed" "MainMenuAdvSquareButtonDepressed"
			"border_disabled" "MainMenuAdvSquareButtonDisabled"
			"bordervisible"			"1"
		}
	}
}
